name: Dev Commit

on:
  push:
    branches:
      - dev

env:
  TF_LOG: ERROR
  TF_ROOT: ${{ github.repository.directory }}
  ARM_CLIENT_ID: ${{ secret.ARM_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_USE_OIDC: true
  ARM_USE_CLI: false
  ARM_SKIP_PROVIDER_REGISTRATION: true
  ARM_ENVIRONMENT: ${{ secrets.ARM_ENVIRONMENT }}
  ARM_OIDC_TOKEN: $ {{ secrets.GITHUB_TOKEN }}

defaults:
  container: hashicorp/terraform:latest
  cache:
    paths:
      - .terraform
      - .terraform.lock.hcl

concurrency: ${{ github.repository }}/${{ github.event.pull_request.head.ref || github.ref }}

jobs:
  Init:
    environment: stc-azure
    if: github.commit_tag == null
    container: hashicorp/terraform:latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Cache Terraform Init
        uses: actions/cache@v3
        with:
          path: .terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles('.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Terraform Init
        id: init
        run: terraform init

  Format:
    environment: stc-azure
    if: github.commit_tag == null
    container: hashicorp/terraform:latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

  Validate:
    environment: stc-azure
    if: github.commit_tag == null
    container: hashicorp/terraform:latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Cache Terraform Init
        uses: actions/cache@v3
        with:
          path: .terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles('.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Terraform Validate
        id: validate
        run: terraform validate

  Test:
    environment: stc-azure
    if: github.commit_tag == null
    container: hashicorp/terraform:latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Cache Terraform Init
        uses: actions/cache@v3
        with:
          path: .terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles('.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Terraform Test
        id: test
        run: terraform test
