name: Dev Commit

on:
  push:
    branches:
      - dev
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  actions: write
  id-token: write

env:
  TF_LOG: ERROR
  TF_ROOT: ${{ github.repository.directory }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_USE_OIDC: true
  ARM_USE_CLI: false
  ARM_SKIP_PROVIDER_REGISTRATION: true
  ARM_ENVIRONMENT: ${{ secrets.ARM_ENVIRONMENT }}


concurrency: ${{ github.repository }}/${{ github.ref }}

jobs:
  Init:
    environment: stc-azure
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Cache Terraform Init
        uses: actions/cache@v3
        with:
          path: |
           .terraform
           .terraform.lock.hcl
          key: ${{ runner.os }}-terraform-${{ hashFiles('.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Terraform Init
        uses: hashicorp/setup-terraform@v3
        id: init
      - run: terraform init

  Format:
    needs: Init
    environment: stc-azure
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Terraform Format
        uses: hashicorp/setup-terraform@v3
        id: fmt
      - run: terraform fmt

  #Validate:
  #  needs: Init
  #  environment: stc-azure
  #  runs-on: ubuntu-latest
  #  container: hashicorp/terraform:latest
  #  if: ${{ !startsWith(github.ref, 'refs/tags/') }}
  #  steps:
  #    - name: Checkout the Repository
  #      uses: actions/checkout@v3

  #    - name: Cache Terraform Init
  #      uses: actions/cache@v2
  #      with:
  #        path: .terraform
  #        key: ${{ runner.os }}-terraform-${{ hashFiles('.terraform.lock.hcl') }}
  #        restore-keys: |
  #          ${{ runner.os }}-terraform-

  #    - name: Terraform Validate
  #      id: validate
  #      run: terraform validate

  Test:
    needs: Init
    environment: stc-azure
    runs-on: ubuntu-latest
    env:
      ARM_OIDC_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Cache Terraform Init
        uses: actions/cache@v3
        with:
          path: |
           .terraform
           .terraform.lock.hcl
          key: ${{ runner.os }}-terraform-${{ hashFiles('.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Az CLI Login
        uses: azure/login@v1.4.6
        with:
          client_id: ${{ secrets.ARM_CLIENT_ID }}
          tenant_id: ${{ secrets.ARM_TENANT_ID }}
          subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          environment: ${{ secrets.AZ_CLI_ENVIRONMENT }}

      - name: Run az commands
        run: az account show

      - name: Terraform Test
        uses: hashicorp/setup-terraform@v3
        id: test
      - run: terraform test
