name: Terraform Module Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

env:
  TF_LOG: ERROR

concurrency: ${{ github.repository }}/${{ github.event.pull_request.head.ref || github.ref }}

jobs:
  terraform-module-release:
    environment: stc-azure
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Release
        uses: cycjimmy/semantic-release-action@v4.0.0
        id: semantic
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/changelog
            @semantic-release/github
            @semantic-release/git
          semantic_version: 1.0.0
          branch: main
